Feature/format chart data
SwanHubX/SwanLab-Dashboard pull request #39
Opened 2024-07-10 13:36 UTC by Feudalman

2024-07-10 13:39 UTC, Feudalman commented on vue/src/utils/chart.js
> +      temp.config = {
这里没有对媒体图表的 config 进行添加：
1. config 中 keys 内容和 metrics 的 column 内容一样（我还没看到有不一样的，不知道有没有特殊情况）
2. config 中包含 index 和 step，这个在本地版后端返回数据中没有

2024-07-11 07:51 UTC, SAKURA-CAT requested changes

2024-07-11 07:51 UTC, SAKURA-CAT commented on vue/src/docs/index.js
> +// @ts-ignore
这个是？

2024-07-11 07:51 UTC, SAKURA-CAT commented on vue/test/utils/chart.test.js
> +  const checkSections = (sections, namespaces) => {
这里没有指定sections的类型

2024-07-11 08:41 UTC, merged