Feat/internationalization
SwanHubX/SwanLab-Dashboard pull request #60
Opened 2024-09-16 08:50 UTC by SIMON-TANG-Liu

zh-CN and en-US switch mutually

2024-09-16 08:59 UTC, Feudalman commented
​​![img_v3_02ep_7c1de37c-ec0e-40d2-b17b-7cae8a840dfg](https://github.com/user-attachments/assets/5329e9b6-5013-4c13-aa0b-42b7aabd7b9c)

taiwindcss 里面有一个 truncate 让文字不会换行

2024-09-16 09:02 UTC, Feudalman commented
![img_v3_02ep_ee8e2952-e416-41dd-bcf3-22db4695807g](https://github.com/user-attachments/assets/f2bd0bdc-9f1e-40f5-8435-afdfb4f9dc03)

1. 如果没有设置语言默认还是英文
2. 如上图，如果设置过有本地缓存以后，框起来的属性也需要随着改变，保持属性和缓存同步

2024-09-16 09:03 UTC, Feudalman commented
> ![img_v3_02ep_ee8e2952-e416-41dd-bcf3-22db4695807g](https://private-user-images.githubusercontent.com/74649535/367697608-f2bd0bdc-9f1e-40f5-8435-afdfb4f9dc03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0Nzc2NTIsIm5iZiI6MTcyNjQ3NzM1MiwicGF0aCI6Ii83NDY0OTUzNS8zNjc2OTc2MDgtZjJiZDBiZGMtOWYxZS00MGY1LTg0MzUtYWZkZmI0ZjlkYzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA5MDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyM2FmNTVmN2ExYzEzN2M0YWYxZjg3YjZmNjZmYjNhYmIyNmZhNzQ1OTVhMzdkOGE1Y2M2NDU5ODNhOWY2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m3UZ_JJ4U-Qr2U-AT4sY9hxeUxMLg48n_M4A5hA-7Lg)
> 
> 1. 如果没有设置语言默认还是英文
> 2. 如上图，如果设置过有本地缓存以后，框起来的属性也需要随着改变，保持属性和缓存同步

这里有缓存的时候一直都是 `en`，不管是中文还是英文

2024-09-16 09:10 UTC, Feudalman commented
中文模式下，有一些地方没有修改到：

![img_v3_02ep_de8647a2-636a-4f4b-b62c-c5ba3a6d24ag](https://github.com/user-attachments/assets/12307399-6d72-41c3-8442-761b76cac58a)

![img_v3_02ep_2e0d2388-ada6-46e3-b763-6158df92f83g](https://github.com/user-attachments/assets/ea87785b-c3f9-4654-b843-28232c2d3e4b)

![img_v3_02ep_d21d7134-4664-4f49-a1c1-d96f4d4ee28g](https://github.com/user-attachments/assets/af3d4081-e77d-44a3-8ec8-4839f2b45f25)

![img_v3_02ep_de699231-f0a3-4141-af90-c03b57aaf1dg](https://github.com/user-attachments/assets/4b46581c-355b-4b7a-9d8c-ed1096f39628)

2024-09-18 06:41 UTC, SAKURA-CAT requested changes

2024-09-18 06:41 UTC, SAKURA-CAT commented on vue/src/i18n/en-US/common.json5
> +      projectChange: 'nothing changed in project config',
关于字段命名约定，应该只有一种约定，camelcase or snake case，这个需要统一一下

2024-09-18 06:41 UTC, SAKURA-CAT commented on vue/src/layouts/main/components/HeaderBar.vue
> +  @apply bg-[#DADDE1];
这个颜色，应该用规定好的颜色

2024-09-19 08:18 UTC, SAKURA-CAT approved these changes

2024-09-19 08:18 UTC, merged